name: release
on:
  push:
    branches:
      - 'master'
      
jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: read
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name:  install twine
        run: |
          pip install twine

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name:  build python
        run: |
          poetry build

      - name: Mint pypi token
        id: mint
        uses: tschm/token-mint-action@v1.0.3

      - name: Publish the package with poetry

        run: |
          twine upload dist/* --verbose
          # poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ steps.mint.outputs.api-token }}